using Vaelorn;
try
{
var catalog=Catalog.Load(File.ReadAllText(Path.Combine(AppContext.BaseDirectory,"catalog.json")));
int passed=0;
void Check(bool condition,string name){if(!condition)throw new Exception("FAIL "+name);Console.WriteLine("PASS "+name);passed++;}
Character Dummy(string id,double hp=10000,double defense=0,string[]? tags=null)=>new(id,id,"test","essence",tags??new[]{"fighter"},new(hp,100,100,defense,100),new[]{"kick"});
var caster=new Unit(Dummy("caster"));
var hits=Rules.Horizon(caster,new[]{new Unit(Dummy("a"),layer:0),new Unit(Dummy("b"),layer:1),new Unit(Dummy("c"),layer:2)});
Check(hits.SequenceEqual(new[]{150d,300d,450d}),"Horizon chains actual prior damage");
hits=Rules.Horizon(caster,new[]{new Unit(Dummy("a",40),layer:0),new Unit(Dummy("b",10000,100),layer:1),new Unit(Dummy("c"),layer:2)});
Check(hits.SequenceEqual(new[]{40d,95d,245d}),"Horizon limits overkill and applies mitigation per target");
var k=new Unit(catalog.Hero("kael"),69,path:"martial");k.OpenGate(20);Check(k.Gate==7&&!k.CanExtreme,"Gate VIII locked below 70");
k=new Unit(catalog.Hero("kael"),70,path:"martial");k.LoseHp(k.MaxHp*.55);Check(k.Gate==2,"Multiple HP thresholds");k.Hp=k.MaxHp;k.LoseHp(k.MaxHp*.55);Check(k.Gate==2,"Thresholds only once after healing");
k=new Unit(catalog.Hero("kael"),70,path:"martial");for(int r=1;r<=16;r++)k.EndRound(r);Check(k.Gate==8&&k.CanExtreme,"Gate advances every two complete rounds");k.PayExtreme();Check(!k.CanExtreme&&k.Hp==k.MaxHp/2,"Extreme once with HP cost");
var baseK=new Unit(catalog.Hero("kael"),70,path:"arsenal");baseK.OpenGate(8);Check(baseK.Gate==0&&baseK.Archetypes.Contains("swordsman"),"Arsenal retains swordsman and has no gates");
var mob=new Unit(Dummy("mob"));mob.ApplyIce(5);Check(!mob.StartOwnTurn()&&mob.Immunity==2,"Freeze consumes exactly one action");mob.ApplyIce(5);Check(mob.Ice==0,"Freeze immunity rejects stacks");
var boss=new Unit(Dummy("boss"),boss:true);boss.ApplyIce(5);Check(boss.StartOwnTurn()&&boss.SlowTurns>0,"Boss receives slow instead of freeze");
var team=Enumerable.Range(0,5).Select(i=>new Unit(Dummy(i.ToString(),tags:i==0?new[]{"fighter","swordsman","weaver"}:new[]{"fighter"}))).ToArray();
Check(Rules.Counts(team)["fighter"]==5&&Rules.Counts(team)["swordsman"]==1,"Multi-archetype counts once per group");
Check(Rules.Fighters(team,team[0])==new Synergy(.10,.30,.12,.15),"Cumulative fighter thresholds");
var save=Game.NewSave();var game=new Game(catalog,save);save.Inventory.Gold=9000;var pulls=game.Summon(10);
Check(pulls.Length==10&&save.Inventory.Gold==0&&!pulls.Contains("varkhan")&&!pulls.Contains("solarius"),"Ten summons cost 9000 and exclude bosses");Check(game.Summon(1).Length==0,"No summon with insufficient gold");
var owned=save.Roster[0];owned.Stars=3;owned.Level=39;owned.Copies=1;Check(!game.Promote(owned.Id)&&owned.Copies==1,"Promotion retains copy below cap");owned.Level=40;Check(game.Promote(owned.Id)&&owned.Stars==4&&owned.Copies==0,"Promotion at cap consumes one copy");
owned.Stars=6;game.GrantCopy(owned.Id);Check(save.Inventory.Jokers==1,"Six-star duplicate becomes joker");
Check(!game.TrainingReward("varkhan",true),"Locked boss cannot be farmed");
var now=save.IdleAt;for(int stage=1;stage<=20;stage++)Check(game.CompleteStage(stage,true,now),"Campaign sequential "+stage);
Check(!game.CompleteStage(20,true,now)&&save.Training.Contains("varkhan"),"Campaign replay refused and Varkhan training unlocked");
Check(!game.TrainingReward("varkhan",true,true)&&save.Inventory.Tickets==3,"Simulation requires previous training win");
Check(!game.TrainingReward("varkhan",false),"Defeat grants no fragments");Check(game.TrainingReward("varkhan",true)&&save.Inventory.Fragments["varkhan"]==1,"Training victory fragments");
Check(game.TrainingReward("varkhan",true,true)&&save.Inventory.Tickets==2,"Simulation consumes ticket");
for(int i=0;i<8;i++)game.TrainingReward("varkhan",true);
Check(game.Reconstruct("varkhan")&&save.Roster.Any(x=>x.Id=="varkhan")&&save.Inventory.Fragments["varkhan"]==0,"Ten fragments reconstruct boss");
for(int stage=21;stage<=70;stage++)game.CompleteStage(stage,true,now);
Check(save.ActComplete&&save.Training.Contains("solarius"),"Solarius unlocks only after act completion");
save=Game.NewSave();game=new Game(catalog,save);now=save.IdleAt;game.Accrue(now.AddDays(30));Check(save.PendingGold==86400,"Idle accumulates 30 days without cap");game.Accrue(now.AddDays(29));Check(save.PendingGold==86400,"Clock rollback grants no extra rewards");
save=Game.NewSave();game=new Game(catalog,save);now=save.IdleAt;game.CompleteStage(1,true,now.AddMinutes(10));game.Accrue(now.AddMinutes(20));Check(save.PendingGold==50,"Idle settles old rate before stage change");
var path=Path.Combine(AppContext.BaseDirectory,"vaelorn-test-"+Guid.NewGuid()+".json");Persistence.Write(path,save);save.Inventory.Gold+=1;Persistence.Write(path,save);Check(Persistence.Read(path).Inventory.Gold==save.Inventory.Gold&&File.Exists(path+".bak"),"Save roundtrip and backup");File.Delete(path);File.Delete(path+".bak");
var battle=new Battle(catalog,new[]{new Unit(catalog.Hero("kael"))},new[]{new Unit(catalog.Hero("enemy_fenda"))});while(!battle.Finished)battle.Step();Check(battle.Won,"Battle ends with victory");
var frozen=new Unit(Dummy("frozen"));frozen.ApplyIce(5);Check(!frozen.StartOwnTurn(),"Freeze skips action");frozen.EndOwnTurn();Check(frozen.Immunity==2,"New immunity does not expire on frozen turn");
frozen.StartOwnTurn();Check(frozen.Immunity==2,"Immunity remains during first protected action");frozen.EndOwnTurn();Check(frozen.Immunity==1,"First protected action consumes one duration");frozen.ApplyIce(5);Check(frozen.Freeze==0,"Immunity blocks refreeze between actions");
frozen.StartOwnTurn();frozen.EndOwnTurn();frozen.ApplyIce(5);Check(frozen.Freeze==1,"Freeze allowed after two protected actions");
var stunned=new Unit(Dummy("stunned"));Check(stunned.ApplyStun(),"Stun accepted by ordinary target");Check(!stunned.StartOwnTurn()&&stunned.SkippedBy=="stun","Stun removes exactly one opportunity");stunned.EndOwnTurn();Check(stunned.StartOwnTurn(),"Unit acts after stun expires");stunned.EndOwnTurn();
stunned.ApplyStun(1);stunned.ApplyStun(1);stunned.StartOwnTurn();stunned.EndOwnTurn();Check(stunned.StartOwnTurn(),"Reapplying stun refreshes rather than adds duration");stunned.EndOwnTurn();
stunned.ApplyStun();stunned.ApplyIce(5);Check(!stunned.StartOwnTurn()&&stunned.SkippedBy=="stun e congelamento","Concurrent controls consume same opportunity");stunned.EndOwnTurn();Check(stunned.StartOwnTurn(),"Concurrent controls do not create extra skipped action");stunned.EndOwnTurn();
var immuneBoss=new Unit(Dummy("boss"),boss:true);Check(!immuneBoss.ApplyStun()&&immuneBoss.Stun==0,"Boss stun immunity provisional default");var vulnerableBoss=new Unit(Dummy("boss"),boss:true,stunImmune:false);Check(vulnerableBoss.ApplyStun(),"Boss stun immunity can be overridden");
var dead=new Unit(Dummy("dead"));dead.LoseHp(dead.MaxHp);Check(!dead.ApplyStun(),"Dead units reject stun");
var first=new Battle(catalog,new[]{new Unit(catalog.Hero("kael"))},new[]{new Unit(catalog.Hero("varkhan"),boss:true)});
var second=new Battle(catalog,new[]{new Unit(catalog.Hero("kael"))},new[]{new Unit(catalog.Hero("varkhan"),boss:true)});
first.Step();second.Advance();second.Advance();Check(first.Log.SequenceEqual(second.Log)&&first.Allies[0].Hp==second.Allies[0].Hp,"Single-action playback matches complete round");
var stunSkill=new Skill("test_stun","Stun de teste","hit","strength",.1,3,Stun:1);
var stunner=Dummy("stunner") with {Skills=new[]{"test_stun"}};
var modified=catalog with {Skills=catalog.Skills.Append(stunSkill).ToArray()};var testTarget=new Unit(Dummy("target") with {Stats=new(10000,100,100,0,50)});
var statusBattle=new Battle(modified,new[]{new Unit(stunner)},new[]{testTarget});statusBattle.Advance();Check(testTarget.Stun==1,"Skill applies configured stun");statusBattle.Advance();Check(statusBattle.LastAction=="stun","Configured skill stun blocks target action");
var manualKael=new Unit(catalog.Hero("kael"));var near=new Unit(Dummy("near"),column:0);var rear=new Unit(Dummy("rear"),column:1,layer:2);
var manualBattle=new Battle(catalog,new[]{manualKael},new[]{near,rear});
Check(!manualBattle.TryAct("winter",rear,out _)&&manualBattle.Round==0&&manualBattle.Log.Count==0,"Foreign skill rejected without consuming turn");
Check(!manualBattle.TryAct("rush",manualKael,out _)&&manualBattle.Round==0,"Offensive skill rejects ally target");
Check(manualBattle.TryAct("rush",rear,out _)&&rear.Hp<rear.MaxHp&&near.Hp==near.MaxHp,"Manual skill damages selected rear target");
Check(manualBattle.Log.Count(x=>x.Contains("Investida"))==4,"Kael rush has four independent hits");
Check(!manualBattle.TryAct("slash",rear,out _),"Manual input cannot control enemy turn");
while(manualBattle.NextActor!=manualKael)manualBattle.Advance();
var beforeInvalid=rear.Hp;Check(!manualBattle.TryAct("rush",rear,out _)&&rear.Hp==beforeInvalid&&manualBattle.Round==1,"Cooldown rejection does not advance round");
rear.LoseHp(rear.MaxHp);Check(!manualBattle.TryAct("slash",rear,out _),"Dead manual target rejected");
var lyra=new Unit(catalog.Hero("lyra"));var rowA=new Unit(Dummy("rowA"),layer:0);var rowB=new Unit(Dummy("rowB"),column:1,layer:0);var back=new Unit(Dummy("back"),layer:1);
var iceBattle=new Battle(catalog,new[]{lyra},new[]{rowA,rowB,back});
Check(!iceBattle.TryAct("winter",rowA,out _)&&iceBattle.Round==0,"Lyra initial cooldown respected in manual mode");
Check(iceBattle.TryAct("glacial",rowB,out _)&&rowA.Ice==2&&rowB.Ice==2&&back.Ice==0,"Chuva Glacial targets selected layer");
while(iceBattle.NextActor!=lyra)iceBattle.Advance();
Check(iceBattle.TryAct("prison",rowB,out _)&&rowB.Freeze==1&&rowB.Ice==0,"Prison completes ice threshold");
while(iceBattle.NextActor!=lyra)iceBattle.Advance();
Check(iceBattle.TryAct("winter",back,out _)&&back.TechniqueSlowTurns==2&&Math.Abs(back.TechniqueSlow-.1)<.001,"Reino Congelado has independent slow");
var slow=new Unit(Dummy("slow"));slow.ApplySlow(.1,2);slow.ApplySlow(.1,2);Check(slow.Speed==90,"Same slow refreshes without multiplying");slow.StartOwnTurn();slow.EndOwnTurn();slow.StartOwnTurn();Check(slow.Speed==90,"Slow lasts through second action");slow.EndOwnTurn();Check(slow.Speed==100,"Slow expires after two complete actions");
var fastHealer=catalog.Hero("aelia") with {Stats=new(1000,20,100,0,300)};var healer=new Unit(fastHealer);var patient1=new Unit(Dummy("patient1"));var patient2=new Unit(Dummy("patient2"));patient1.LoseHp(9000);patient2.LoseHp(1000);
var healingBattle=new Battle(catalog,new[]{healer,patient1,patient2},new[]{new Unit(Dummy("foe"))});
Check(healingBattle.TryAct("heal",patient2,out _)&&patient1.Hp==1000&&patient2.Hp==9250,"Manual healing respects chosen ally");
var martial=new Unit(catalog.Hero("kael"),70,path:"martial");var martialBattle=new Battle(catalog,new[]{martial},new[]{new Unit(Dummy("bag",100000))});
Check(!martialBattle.TryAct("martial_beast",martialBattle.Enemies[0],out _)&&martialBattle.Round==0,"Fera Carmesim requires gate VI");
Check(martialBattle.TryAct("martial_break",null,out _)&&martial.Gate==1&&martial.Hp<martial.MaxHp,"Manual gate acceleration accepts no target");
while(martialBattle.NextActor!=martial)martialBattle.Advance();
Check(martialBattle.TryAct("martial_impact",martialBattle.Enemies[0],out _),"Martial impact is a selectable skill");
while(martialBattle.NextActor!=martial)martialBattle.Advance();
Check(!martialBattle.TryAct("martial_impact",martialBattle.Enemies[0],out _),"Martial impact respects CD 3");
var trainingSave=Game.NewSave();var trainingGame=new Game(catalog,trainingSave);
Check(trainingGame.BeginTraining("varkhan")==null,"Three-wave training requires unlock");
trainingSave.Training.Add("varkhan");var run=trainingGame.BeginTraining("varkhan")!;
Check(run.Wave==1&&run.Current.Enemies.Count==3&&!run.ClaimReward(),"Wave one gives no early reward");
var survivor=run.Current.Allies[0];survivor.LoseHp(200);survivor.ApplyIce(2);survivor.ReadyRound["rush"]=6;
foreach(var target in run.Current.Enemies)target.LoseHp(target.MaxHp);
Check(run.NextWave()&&run.Wave==2&&run.Current.Enemies.Count==5,"Wave two follows victory");
Check(ReferenceEquals(survivor,run.Current.Allies[0])&&survivor.Hp==survivor.MaxHp-200&&survivor.Ice==2&&survivor.ReadyRound["rush"]==6,"Training preserves HP controls and cooldowns");
Check(!run.ClaimReward()&&trainingSave.Inventory.Fragments.Count==0,"No fragments before final boss");
foreach(var target in run.Current.Enemies)target.LoseHp(target.MaxHp);
Check(run.NextWave()&&run.Wave==3&&run.Current.Enemies.Single().Id=="varkhan","Boss is third wave");
foreach(var target in run.Current.Enemies)target.LoseHp(target.MaxHp);
Check(run.ClaimReward()&&trainingSave.Inventory.Fragments["varkhan"]==1,"Completed three-wave run awards fragments");
Check(!run.ClaimReward()&&!run.NextWave()&&trainingSave.Inventory.Fragments["varkhan"]==1,"Training run cannot grant twice or create fourth wave");
var failedRun=trainingGame.BeginTraining("varkhan")!;foreach(var ally in failedRun.Current.Allies)ally.LoseHp(ally.MaxHp);
Check(!failedRun.NextWave()&&!failedRun.ClaimReward()&&failedRun.Finished,"Training defeat stops waves without reward");
// Presentation events must reflect actual resolved damage, not inferred HP totals.
var eventKael=new Unit(catalog.Hero("kael"),20);
var eventVictim=new Unit(Dummy("events",50000) with {Stats=new Stats(50000,1,1,30,1)});
var eventBattle=new Battle(catalog,new[]{eventKael},new[]{eventVictim});
var eventHp=eventVictim.Hp;
Check(eventBattle.TryAct("rush",eventVictim,out _),"Impact test casts rush");
Check(eventBattle.LastImpacts.Count==4&&eventBattle.LastImpacts.All(e=>e.Kind=="physical")&&eventBattle.LastImpacts.Select(e=>e.HitIndex).SequenceEqual(new[]{0,1,2,3}),"Physical hits retain individual timing and type");
Check(Math.Abs(eventBattle.LastImpacts.Sum(e=>e.Amount)-(eventHp-eventVictim.Hp))<.0001,"Impact numbers equal effective HP loss");
eventBattle.Advance();Check(eventBattle.LastImpacts.All(e=>e.Target==eventKael),"Events reset between actions");
var eventLyra=new Unit(catalog.Hero("lyra"),20);eventVictim=new Unit(Dummy("ice-events") with {Stats=new Stats(10000,1,1,0,1)});
eventBattle=new Battle(catalog,new[]{eventLyra},new[]{eventVictim});eventBattle.TryAct("ice",eventVictim,out _);
Check(eventBattle.LastImpacts.Count==1&&eventBattle.LastImpacts[0].Kind=="essence","Essence attacks labeled by actual skill scale");
var eventHealer=new Unit(catalog.Hero("aelia"),20);eventHealer.Hp-=20;
eventBattle=new Battle(catalog,new[]{eventHealer},new[]{new Unit(Dummy("heal-events") with {Stats=new Stats(10000,1,1,0,1)})});eventHealer.ReadyRound["heal"]=0;
eventBattle.TryAct("heal",eventHealer,out _);
Check(eventBattle.LastImpacts.Single().Kind=="heal"&&Math.Abs(eventBattle.LastImpacts[0].Amount-20)<.0001&&!eventBattle.LastImpacts[0].Critical,"Healing event reports effective healing without fake crit");
bool sawCritical=false;
for(int seed=0;seed<100&&!sawCritical;seed++){
 var hero=new Unit(catalog.Hero("kael"),20);var victim=new Unit(Dummy("crit-events") with {Stats=new Stats(10000,1,1,0,1)});
 var encounter=new Battle(catalog,new[]{hero},new[]{victim},seed);encounter.TryAct("rush",victim,out _);
 sawCritical=encounter.LastImpacts.Any(e=>e.Critical);
 if(sawCritical)Check(encounter.LastImpacts.Count(e=>e.Critical)==encounter.Log.Count(l=>l.Contains("crítico")),"Critical flags match resolved combat log");
}
Check(sawCritical,"Critical event exercised");
Check(new Unit(catalog.Hero("varkhan")).SurvivesDefeat,"Story boss protected even outside boss encounter");
Check(new Unit(catalog.Hero("enemy_fenda"),boss:true).SurvivesDefeat,"Any boss survives narrative defeat");
Check(!new Unit(catalog.Hero("enemy_fenda")).SurvivesDefeat,"Ordinary enemy has no story protection");
Check(new Unit(catalog.Hero("kael")).SurvivesDefeat,"Main character protected");
// Cooking abilities are real temporary buffs, without damage or a required enemy target.
var chefDef=catalog.Hero("savor") with {Stats=new Stats(1200,100,30,35,200)};
var chef=new Unit(chefDef);var receiver=new Unit(catalog.Hero("aelia"));
var buffEnemy=new Unit(Dummy("buff-enemy") with {Stats=new Stats(50000,1,1,0,1)});
var buffBattle=new Battle(catalog,new[]{chef,receiver},new[]{buffEnemy});
Check(buffBattle.TryAct("first_fish",null,out _),"Speed meal accepts no target");
Check(Math.Abs(receiver.Speed-110)<.001&&Math.Abs(chef.Speed-220)<.001,"Meal boosts all living ally speeds by ten percent");
Check(buffBattle.LastImpacts.Count==0&&buffEnemy.Hp==buffEnemy.MaxHp&&buffBattle.LastBuffTargets.Count==2,"Buff emits recipients without damage");
Check(chef.ReadyRound["first_fish"]==4,"Meal cooldown is three rounds");
receiver.ApplyBuff("first_fish",new(0,0,.1,2));Check(Math.Abs(receiver.Speed-110)<.001,"Same meal refreshes without multiplying itself");
receiver.EndRound(1);Check(receiver.BuffSpeed==.1,"Meal persists through first round");receiver.EndRound(2);Check(receiver.BuffSpeed==0&&receiver.Speed==100,"Meal expires after second round");
chef=new Unit(chefDef with {Stats=chefDef.Stats with {Strength=200}});receiver=new Unit(catalog.Hero("aelia"));
buffBattle=new Battle(catalog,new[]{chef,receiver},new[]{buffEnemy});
Check(buffBattle.TryAct("chef_pride",null,out _)&&chef.Strength==300&&receiver.Essence==210&&receiver.Strength==60,"Strongest chef grants both offense bonuses to team");
chef=new Unit(chefDef);receiver=new Unit(catalog.Hero("kael") with {Stats=catalog.Hero("kael").Stats with {Speed=90}});
buffBattle=new Battle(catalog,new[]{chef,receiver},new[]{buffEnemy});buffBattle.TryAct("chef_pride",null,out _);
Check(buffBattle.LastBuffTargets.Count==1&&receiver.Strength==210&&receiver.BuffEssence==0&&chef.BuffStrength==0,"Weaker chef buffs strongest primary offense only");
var fallenBuff=new Unit(catalog.Hero("aelia"));fallenBuff.LoseHp(fallenBuff.Hp);fallenBuff.ApplyBuff("meal",new(.5,.5,.1,2));Check(fallenBuff.Buffs.Count==0,"Fallen allies reject food buffs");
// Formation accepts every one of the nine cells, swaps atomically and locks before combat.
Check(Formation.Normalize(new[]{8,8,-1,20,4},5).SequenceEqual(new[]{8,0,1,2,4}),"Invalid or duplicated saved cells normalize deterministically");
Check(Formation.Normalize(null,5).Distinct().Count()==5,"Missing formation migrates to unique cells");
var formationHeroes=new[]{new Unit(catalog.Hero("kael")),new Unit(catalog.Hero("savor"),column:1)};
var formationBattle=new Battle(catalog,formationHeroes,new[]{new Unit(Dummy("formation-target"))});
Check(formationBattle.TryMoveAlly(formationHeroes[0],1)&&formationHeroes[1].Column==0,"Occupied cell swaps both allies");
for(int cell=0;cell<9;cell++)Check(formationBattle.TryMoveAlly(formationHeroes[0],cell)&&formationHeroes[0].Column==cell%3&&formationHeroes[0].Layer==cell/3,"Formation reaches cell "+cell);
Check(!formationBattle.TryMoveAlly(formationHeroes[0],9)&&!formationBattle.TryMoveAlly(formationBattle.Enemies[0],0),"Invalid cells and enemy movement rejected");
formationBattle.LockFormation();Check(!formationBattle.TryMoveAlly(formationHeroes[0],0),"Formation locks before first action");
var formSave=Game.NewSave();formSave.FormationCells=new(){8,2,4,6,0};formSave.CompletedStage=20;formSave.Training.Add("varkhan");
var formRun=new Game(catalog,formSave).BeginTraining("varkhan")!;
Check(formRun.Current.Allies.Select(u=>u.Layer*3+u.Column).SequenceEqual(formSave.FormationCells),"Training respects saved 3x3 formation");
var formedAgain=System.Text.Json.JsonSerializer.Deserialize<SaveData>(System.Text.Json.JsonSerializer.Serialize(formSave))!;
Check(formedAgain.FormationCells.SequenceEqual(formSave.FormationCells),"Formation persists through save serialization");
var laneCaster=new Unit(Dummy("lane-caster"));var laneTargets=Enumerable.Range(0,3).Select(layer=>new Unit(Dummy("lane-"+layer),column:2,layer:layer)).ToArray();
Check(Rules.Horizon(laneCaster,laneTargets).SequenceEqual(new[]{150d,300d,450d}),"Third column supports chained three-layer horizon");
// Ordinary campaign replays and boss gates are separate from sequential completion.
var replaySave=Game.NewSave();var replayGame=new Game(catalog,replaySave);
Check(replayGame.CanEnterStage(1)&&!replayGame.CanEnterStage(2),"Only first stage initially accessible");
Check(!replayGame.CanEnterStage(0)&&!replayGame.CanEnterStage(71),"Invalid campaign stages rejected");
Check(replayGame.RewardCampaignEncounter(1,true,now),"First clear rewards and progresses");
var firstGold=replaySave.Inventory.Gold;var firstXp=replaySave.Inventory.Xp;
Check(replayGame.RewardCampaignEncounter(1,true,now)&&replaySave.CompletedStage==1&&replaySave.Inventory.Gold==firstGold+catalog.Stages.Single(s=>s.Number==1).Gold,"Ordinary replay rewards Gold without advancing");
Check(replaySave.Inventory.Xp==firstXp&&replaySave.Training.Count==0&&replaySave.Inventory.Fragments.Count==0,"Replay grants no XP fragments or boss unlocks");
var repeatGold=replaySave.Inventory.Gold;
Check(!replayGame.RewardCampaignEncounter(1,false,now)&&replaySave.Inventory.Gold==repeatGold,"Replay defeat grants nothing");
Check(!replayGame.RewardCampaignEncounter(3,true,now)&&replaySave.CompletedStage==1,"Future stage cannot grant reward");
for(int n=2;n<=9;n++)replayGame.RewardCampaignEncounter(n,true,now);
Check(replayGame.CanEnterStage(10)&&!replayGame.CanEnterStage(11),"Next region blocked before boss");
Check(replayGame.RewardCampaignEncounter(10,true,now)&&replayGame.CanEnterStage(11),"Boss completion opens next region");
var bossGold=replaySave.Inventory.Gold;
Check(!replayGame.CanEnterStage(10)&&!replayGame.RewardCampaignEncounter(10,true,now)&&replaySave.Inventory.Gold==bossGold,"Completed boss cannot replay or grant reward");
Check(replayGame.CanEnterStage(9),"Ordinary island stays replayable after region boss");

var bleed=catalog.StatusEffects.Single(s=>s.Id=="bleed");var exposed=catalog.StatusEffects.Single(s=>s.Id=="exposed");
var beast=new Unit(catalog.Hero("varkas"));var prey=new Unit(Dummy("prey",100000),boss:true);
prey.AddStatus(bleed,beast);double snapshot=beast.Strength;beast.ApplyBuff("test",new(1,0,0,99));
var ticks=prey.TickDamageStatuses();Check(ticks.Single().Damage==snapshot*.15,"Bleed snapshots original source strength, ignoring later buffs and boss immunity");
var other=new Unit(catalog.Hero("varkas"),2);prey.AddStatus(bleed,other);Check(prey.Statuses.Select(x=>x.SourceInstance).Distinct().Count()==2,"Same-character sources have distinct origin identities");
prey.TickDamageStatuses();prey.TickDamageStatuses();Check(prey.Stacks("bleed")==1&&prey.Statuses[0].RemainingTurns==1,"Bleed stacks expire independently after three victim turns");prey.TickDamageStatuses();Check(prey.Stacks("bleed")==0,"Last independent bleed expires");
for(int n=0;n<12;n++)prey.AddStatus(bleed,beast);Check(prey.Stacks("bleed")==10,"Bleed cap ten");
prey.AddStatus(exposed,beast);Check(Math.Abs(prey.IncomingStatusChance("bleed",.4)-.65)<.0001&&Math.Abs(prey.IncomingStatusChance("bleed",.6)-.85)<.0001,"Exposed adds percentage points to base and enhanced chance");prey.EndStatusTurn();Check(prey.Stacks("exposed")==1,"Exposed survives first turn");prey.EndStatusTurn();Check(prey.Stacks("exposed")==0,"Exposed lasts two turns");
var splitSkill=catalog.Ability("duality");beast=new Unit(catalog.Hero("varkas"));beast.Hp=beast.MaxHp*.69;Check(!beast.Split(splitSkill),"Duality rejects below 70 percent");beast.Hp=beast.MaxHp*.7;double oldHp=beast.Hp;double maximum=beast.MaxHp;Check(beast.Split(splitSkill),"Duality accepts exactly 70 percent");var spirit=beast.Duality!.Spirit;
Check(Math.Abs(beast.Hp-oldHp*.6)<.001&&Math.Abs(spirit.Hp-oldHp*.4)<.001&&beast.MaxHp+spirit.MaxHp==maximum,"Duality preserves current and maximum HP totals");
Check(Rules.Counts(beast.TargetForms)["fighter"]==1&&Rules.Counts(beast.TargetForms)["predator"]==1,"Linked forms count as one for every synergy");
beast.ApplyBuff("food",new(.1,0,0,99));Check(spirit.BuffStrength==beast.BuffStrength,"Spirit shares owner's buffs without duplicate application");
spirit.LoseHp(spirit.Hp);Check(beast.Duality==null&&beast.Hp==maximum*.3&&!spirit.Alive&&!beast.Split(splitSkill),"Spirit death merges immediately, returns 30 percent, prevents second use");
beast=new Unit(catalog.Hero("varkas"));beast.Split(splitSkill);beast.LoseHp(beast.Hp);Check(beast.Duality==null&&beast.Hp==beast.MaxHp*.3,"Body death also merges immediately");
var vb=new Unit(catalog.Hero("varkas"),30);var vp=new Unit(Dummy("target",100000));var duel=new Battle(catalog,new[]{vb},new[]{vp});
Check(duel.TryAct("duality",null,out var ve)&&duel.Allies.Count==1&&duel.AlliedTargets.Count==2,"Split creates two targets without adding a team slot");
duel.Advance();Check(duel.NextActor==vb,"Spirit has no independent action or turn");
Check(duel.TryAct("gale_fangs",vp,out ve)&&duel.LastImpacts.Count==10,"Five random hits copied as five spirit hits");
var normalized=duel.LastImpacts.Select(x=>x.Amount/(x.Critical?1.5:1)).ToArray();Check(Math.Abs(normalized[5]/normalized[0]-.6)<.0001,"Spirit damage modifier exactly sixty percent");
Check(duel.UnavailableReason(vb,splitSkill)!="","Duality remains unavailable while split or used");
foreach(int stackCount in new[]{0,5,10}){
 var v=new Unit(catalog.Hero("varkas"));var t=new Unit(Dummy("mark",100000));for(int n=0;n<stackCount;n++)t.AddStatus(bleed,v);var b=new Battle(catalog,new[]{v},new[]{t});b.TryAct("marked",t,out _);var impact=b.LastImpacts.Single();Check(Math.Abs(impact.Amount/(impact.Critical?1.5:1)-v.Strength*1.8*(1+.1*stackCount))<.001,"Marked damage matches stacks "+stackCount);Check(t.Stacks("bleed")>=stackCount,"Marked never consumes bleed "+stackCount);
}
var lowBeast=new Unit(catalog.Hero("varkas"));var lockBattle=new Battle(catalog,new[]{lowBeast},new[]{new Unit(Dummy("lock"))});Check(lockBattle.UnavailableReason(lowBeast,catalog.Ability("lacerate")).Contains("30"),"Advanced skill level lock data driven");
var rewardSave=Game.NewSave();var rewardGame=new Game(catalog,rewardSave);var goldBefore=rewardSave.Inventory.Gold;
Check(rewardGame.RewardCampaignEncounter(1,true,now)&&rewardSave.Inventory.Gold==goldBefore+1000,"Campaign grants exactly 1000 gold");
Check(rewardSave.Roster.All(o=>o.Level==3&&o.BattleXp==25),"500 XP split across five members, levels and remainder retained");
Check(rewardGame.LastCampaignReward.Contains("XP")&&rewardGame.LastCampaignReward.Contains("Kael"),"Reward receipt lists participant XP");
var xpBefore=rewardSave.Roster.Sum(o=>o.BattleXp);
var guestSave=Game.NewSave();var guestGame=new Game(catalog,guestSave);
guestGame.RewardCampaignEncounter(1,true,now,new[]{"kael","savor","aelia","brakk","raizen"});
Check(guestSave.Roster.Single(x=>x.Id=="lyra").BattleXp==0&&guestSave.CampaignGuests.Single(x=>x.Id=="raizen").Level==3&&!guestSave.Roster.Any(x=>x.Id=="raizen"),"Only actual participants receive XP; guest progress saved without unlocking");
Check(!rewardGame.RewardCampaignEncounter(2,false,now)&&rewardSave.Roster.Sum(o=>o.BattleXp)==xpBefore,"Defeat never grants individual XP");
rewardSave.Team=new(){"kael"};rewardSave.Roster[0].Level=Game.LevelCap(rewardSave.Roster[0].Stars);
rewardGame.RewardCampaignEncounter(1,true,now);
Check(rewardSave.Roster[0].BattleXp==525,"Capped hero retains battle XP; absent members receive none");
var xpPath=Path.Combine(AppContext.BaseDirectory,"reward-"+Guid.NewGuid()+".json");Persistence.Write(xpPath,rewardSave);
Check(Persistence.Read(xpPath).Roster[0].BattleXp==525,"Individual campaign XP persists");File.Delete(xpPath);
Check(catalog.Hero("varkas").Name=="Fenrath","Rename preserves stable save ID");
Check(catalog.Stages.Single(s=>s.Number==50).BossId=="nerathis","Floral boss placed at provisional scenario five finale");
var flowerDef=catalog.Hero("nerathis") with{Stats=new Stats(1000,10,10,0,999),CritChance=0,Skills=new[]{"flower_petals"}};
var flower=new Unit(flowerDef,1,true);var flowerVictim=new Unit(Dummy("flower_target",10000));
var floralBattle=new Battle(catalog,new[]{flowerVictim},new[]{flower});floralBattle.Advance();
Check(Math.Abs(floralBattle.LastImpacts.Single().Amount-818)<.001,"Petals combines eight percent target HP and 180 percent attack");
Check(flowerVictim.Stacks("poison")==1&&flowerVictim.Stacks("venom_burn")==1,"Floral passive and burn applied");
Check(Math.Abs(flowerVictim.OutgoingDamage-.8)<.001,"Burn reduces outgoing damage twenty percent");
var poisonTicks=flowerVictim.TickDamageStatuses();Check(Math.Abs(poisonTicks.Sum(x=>x.Damage)-605)<.001,"Poison and burn use target HP plus source attack snapshot");
var thornCaster=new Unit(flowerDef with{Skills=new[]{"flower_thorns"}},1,true);
var thornVictim=new Unit(Dummy("thorn_target",10000));for(int n=0;n<3;n++)thornVictim.AddStatus(catalog.StatusEffects.Single(s=>s.Id=="poison"),thornCaster);
var thornBattle=new Battle(catalog,new[]{thornVictim},new[]{thornCaster});thornBattle.Advance();
Check(Math.Abs(thornBattle.LastImpacts.Single().Amount-35)<.001,"Thorns gains forty percent against three poison stacks");
Check(thornVictim.Stacks("poison")==5&&thornVictim.Stacks("deep_poison")==1,"Poison caps at five and triggers deep poisoning");
Check(Math.Abs(thornVictim.VulnerabilityFrom(thornCaster)-.25)<.001&&thornVictim.VulnerabilityFrom(flower)==0,"Deep poison only amplifies its source");
Check(Math.Abs(thornVictim.StatusReduction(e=>e.HealReduction)-.1)<.001,"Thorns reduces received healing");
flower.LoseHp(510);Check(flower.Crimson&&Math.Abs(flower.OutgoingDamage-1.2)<.001&&Math.Abs(flower.Speed-1148.85)<.001,"Crimson phase damage and speed thresholds");
flower.LoseHp(250);Check(flower.Blooming,"Blooming activates below twenty five percent");
var sleepCatalog=catalog with{Skills=catalog.Skills.Select(s=>s.Id=="flower_sleep"?s with{InitialCooldown=0}:s).ToArray()};
var sleeper=new Unit(flowerDef with{Skills=new[]{"flower_sleep"},Floral=new FloralKit(SleepChance:1)},1,true);
var sleepingBoss=new Unit(Dummy("sleep_boss",10000),1,true);
var sleepBattle=new Battle(sleepCatalog,new[]{sleepingBoss},new[]{sleeper});sleepBattle.Advance();
Check(sleepingBoss.Statuses.Single(s=>s.Effect.Sleep).RemainingTurns==1,"Boss sleep lasts only one turn");
Check(!sleepingBoss.StartOwnTurn()&&sleepingBoss.SkippedBy=="sono","Sleep blocks actions");
sleepingBoss.EndStatusTurn();Check(!sleepingBoss.Statuses.Any(s=>s.Effect.Sleep),"Sleep expires independently");

Check(catalog.Hero("nerathis").Name=="Velmora"&&catalog.Stages.Single(s=>s.Number==60).BossId=="maltherion","Confirmed bosses at 50 and 60");
Check(catalog.Summon.Pool.Contains("sevrin")&&!catalog.Summon.Pool.Contains("maltherion"),"Swordsman uses farmable gold summons, boss excluded");
var eclipse=new Unit(catalog.Hero("maltherion"));var preDefense=eclipse.Defense;
eclipse.LoseHp(eclipse.MaxHp*.5);
Check(eclipse.Ascended&&eclipse.Defense>preDefense&&eclipse.ControlResistance==.8,"Eclipse transforms at exactly half HP");
eclipse.Hp=eclipse.MaxHp;Check(eclipse.Ascended,"Ascension survives healing");
for(int n=0;n<12;n++)eclipse.RegisterHit(1);
Check(eclipse.Carnage==7&&Math.Abs(eclipse.CriticalChance-.62)<.001,"Ascended carnage cap and critical chance");
eclipse.EndRound(3);Check(eclipse.Carnage==5,"Carnage decays after two rounds without hits");
var sevrin=new Unit(catalog.Hero("sevrin"));var scarletPrey=new Unit(Dummy("scarletPrey",50000));
Check(sevrin.ProtectionFrom(scarletPrey)==.25,"Front formation protects from healthy attackers");
var scarletRear=new Unit(catalog.Hero("sevrin"),layer:1);var scarletRearBattle=new Battle(catalog,new[]{scarletRear},new[]{scarletPrey});
Check(scarletRearBattle.UnavailableReason(scarletRear,catalog.Ability("scarlet_front")).Contains("frente"),"Front skill rejected from scarletRear");
var bleedDef=catalog.StatusEffects.Single(s=>s.Id=="scarlet_bleed");
for(int n=0;n<8;n++)scarletPrey.AddStatus(bleedDef,sevrin);
Check(scarletPrey.BleedCount==5,"Scarlet bleed limited to five charges");
scarletPrey.AddStatus(catalog.StatusEffects.Single(s=>s.Id=="scarlet_bleed_ii"),sevrin);
Check(scarletPrey.BleedCount==5&&scarletPrey.Statuses.Any(s=>s.Effect.Id=="scarlet_bleed_ii"),"Strong bleed upgrades within five-charge cap");
var scarletBattle=new Battle(catalog,new[]{sevrin},new[]{scarletPrey});
Check(scarletBattle.TryAct("scarlet_quick",scarletPrey,out var scarletError),"Quick slash selectable");
Check(scarletBattle.LastImpacts.Count==2,"Already bleeding target receives second slash");
var guardTarget=new Unit(Dummy("guard"));guardTarget.AddStatus(catalog.StatusEffects.Single(s=>s.Id=="demon_guard"),eclipse);
Check(Math.Abs(Rules.Hit(guardTarget,100)-70)<.001,"Demon guard mitigates incoming damage");
var phaseBattle=new Battle(catalog,new[]{eclipse},new[]{new Unit(Dummy("survivor",100000))});
Check(phaseBattle.SkillsFor(eclipse).Any(s=>s.Id=="eclipse_final")&&!phaseBattle.SkillsFor(eclipse).Any(s=>s.Id=="eclipse_axe"),"Ascended action list replaces axe with bone blade");

foreach(var ability in catalog.Skills.Where(s=>s.Id.StartsWith("scarlet_")||s.Id.StartsWith("eclipse_"))){
    var definition=catalog.Hero(ability.Id.StartsWith("scarlet_")?"sevrin":"maltherion");
    var testActor=new Unit(definition with {Stats=definition.Stats with {Speed=999}});
    if(ability.Id is "eclipse_bone" or "eclipse_triple" or "eclipse_final")testActor.LoseHp(testActor.MaxHp*.51);
    var victim=new Unit(Dummy("kit-victim",100000));
    var kitBattle=new Battle(catalog,new[]{testActor},new[]{victim});testActor.ReadyRound[ability.Id]=1;
    Check(kitBattle.TryAct(ability.Id,victim,out var kitError),"Kit executable: "+ability.Id+" "+kitError);
    Check(kitBattle.LastImpacts.Any(h=>h.Amount>0)||kitBattle.LastBuffTargets.Contains(testActor),"Kit has actual effect: "+ability.Id);
}
var dotHero=new Unit(catalog.Hero("sevrin") with {Stats=catalog.Hero("sevrin").Stats with {Speed=1}});dotHero.Hp=dotHero.MaxHp*.5;
var dotVictim=new Unit(Dummy("dot-victim",10));dotVictim.AddStatus(bleedDef,dotHero);dotVictim.Statuses[0].RemainingTurns=1;
var dotBattle=new Battle(catalog,new[]{dotHero},new[]{dotVictim});dotHero.ReadyRound["scarlet_quick"]=5;dotBattle.Advance();
Check(!dotVictim.Alive&&dotHero.Hp>dotHero.MaxHp*.5&&dotHero.ReadyRound["scarlet_quick"]==4,"Final bleed tick awards heal and cooldown refund");
Console.WriteLine($"{passed} assertions passed.");
}
catch(Exception ex)
{
    Console.Error.WriteLine("Teste interrompido: "+ex.Message);
    Console.Error.WriteLine("Se o erro for acesso negado ao substituir o save, execute em uma pasta local gravável fora do ambiente restrito. Nenhum save do jogo é usado pelos testes.");
    Environment.ExitCode=1;
}

